version: '3'
services:
  manager:
    build: .
    container_name: manager
    networks:
      - mpi_network

  worker:
    build: .
    container_name: worker
    networks:
      - mpi_network
    depends_on:
      - manager

networks:
  mpi_network: