version: '3.8'

services:
  mpi-master:
    build: .
    container_name: mpi-master
    networks:
      - mpi_network
    command: ["mpiexec", "-n", "2", "--host", "mpi-master,mpi-worker", "python3", "/app/mpi_prime.py"]

  mpi-worker:
    build: .
    container_name: mpi-worker
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge